# Generated by Django 4.2.20 on 2025-03-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=100)),
                ('license_plate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('detection_time', models.DateTimeField(auto_now_add=True)),
                ('original_image', models.ImageField(upload_to='violations/original/')),
                ('detected_image', models.ImageField(upload_to='violations/detected/')),
            ],
        ),
    ]
