# Generated by Django 4.2.20 on 2025-04-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_violationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationrecord',
            name='incident_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='violationrecord',
            name='incident_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='violationrecord',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='violationrecord',
            name='location_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
