# Generated by Django 4.2.20 on 2025-04-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_violationrecord_incident_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationrecord',
            name='plate_image',
            field=models.ImageField(blank=True, null=True, upload_to='plates/'),
        ),
    ]
